# Site settings
title: Banjara Community Blog
description: >
  A blog dedicated to sharing information and stories about the Banjara
  community. Available in multiple languages including English, Telugu, and
  Hindi.
baseurl: "" # The subpath of your site, e.g. /blog
url: "https://gormaati.github.io" # Replace with your site's URL
twitter_username: Gormati
github_username: Gormaati

# Multilingual settings
languages: ["en", "te", "hi"]

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Permalink configuration
permalink: /:categories/:year/:month/:day/:title.html

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Uncomment and modify this section if you need specific configurations
# markdown: kramdown
# kramdown:
#   input: GFM

# Uncomment to include any other Jekyll plugins or configurations
# plugins:
#   - jekyll-seo-tag
#   - jekyll-sitemap
#   - jekyll-paginate

