# Site settings
title: Gormati Blog
email: naveenkorra2014@gmail.com
description: >-
  A blog dedicated to sharing information and stories about the Gormati community.
  Available in multiple languages including English, Telugu, and Hindi.
baseurl: "" # Leave empty if your site is at the root of your GitHub Pages site
url: "https://gormaati.github.io/blog" # URL of your GitHub Pages site
twitter_username: Gormati
github_username: Gormaati

# Multilingual settings
languages: ["en", "te", "hi"]

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - docs/
  - notebooks/

# Include files in _posts
include:
  - _posts/

