# Site settings
title: Gormatti Blog
email: gormattibanjara@gmail.com
description: >-
  A blog dedicated to sharing information and stories about the Gormatti community.
baseurl: "/blogs/docs" # Adjust this to the directory structure
url: "https://gormaati.github.io" # Your GitHub Pages URL

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock

