# Site settings
title: Gormatti Blog
email: naveenkorra2014@gmail.com
description: >-
  A blog dedicated to sharing information and stories about the Gormatti community.
baseurl: "/blog"  # Adjust if needed
url: "https://gormaati.github.io"  # Base URL for your site

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - node_modules
  - vendor/

