source "https://rubygems.org"

# Use specific Jekyll and theme versions
gem "jekyll", "~> 4.2.0"
gem "minima", "~> 2.5"

# Use github-pages gem for GitHub Pages compatibility
gem "github-pages", group: :jekyll_plugins

# Add any additional plugins or dependencies needed
group :jekyll_plugins do
  gem "jekyll-feed", "~> 0.15"
end

# Windows and JRuby do not include zoneinfo files, so bundle the
# tzinfo-data gem and associated library.
platforms :mingw, :x64_mingw, :mswin, :jruby do
  gem "tzinfo", ">= 1", "< 4"
  gem "tzinfo-data"
end

# Performance-booster for watching directories on Windows
gem "wdm", "~> 0.1.1", platforms: [:mingw, :x64_mingw, :mswin]

